### ISSUE TITLE
pandas issue: typo in roadmap

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/pandas-mentoring#82]
Just realized that the recently created pandas roadmap has a typo. In the section https://dev.pandas.io/development/roadmap.html#decoupling-of-indexing-and-internals the `uses` word is duplicated.

If anybody here wants to fix that, you should already know how to open a PR not using `master` ;)

Please add a comment in this issue if you're taking this, and if someone does don't also work on the same, that's not nice (open source is about working as a team, there is no competition at all, not even among different projects doing the same). Also, make sure there is not a PR in pandas already open for this.

The file to edit should be `doc/source/development/roadmap.md` (didn't check in detail).

**Comment by MKhalusova** [comment]
I can take this.

**Comment by MKhalusova** [comment]
@datapythonista when creating a PR, I get pre-filled description 
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

What am I supposed to do with it if it's just a fix for a typo in an .rst file? Just delete it? cause it doesn't make sense in this context really. Or should I leave it as is?

**Comment by datapythonista** [comment]
In this case nothing applies, so I think leaving it as is, or removing it are both correct options. I usually remove it for a change like this.

**Comment by MKhalusova** [comment]
Thanks! Created a PR: https://github.com/pandas-dev/pandas/pull/27710

**Comment by datapythonista** [comment]
Approved it already. :)

Even for something that small the process is usually to wait for the CI to be green (it takes around 30 minutes, and some times fails for things unrelated to the PR), then one maintainer approves, an another one merges. The most senior maintainers would probably merged if it's a typo even if it's not approved.

Welcome to the pandas team, feel free to close this issue once the PR is merged. And if you thing there is something worth sharing (technical or not) about this, feel free to send an email to the group.

**Comment by MKhalusova** [comment]
Woohoo! This feels great! 💃 
<img width="798" alt="Screen Shot 2019-08-02 at 9 30 51 AM" src="https://user-images.githubusercontent.com/1065417/62373661-4a27d100-b508-11e9-81ef-c23572af3812.png">

**Comment by MKhalusova** [comment]
I don't think I have permissions to close this issue though.

**Comment by MKhalusova** [comment]
Never mind, now that I joined the organization, I can close the issue

**Comment by datapythonista** [comment]
added you to the organization, hopefully that helps with this and with gitter :)

Btw, if you think it's useful, you can also add a section in the README (or a separate markdown) to have the list of pandas contributions we make. Not sure if it's a good idea or not.
